environments: dev
logging:
  path: /data/logs/
  #显示 SQL
  level:
    org:
      goskyer:
        mapper: debug
server:
  port: 7801



spring:
  application:
    name: springboot-seed
  profiles:
    active: dev
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  #  cache:
  #    ehcache:
  #      config: classpath:config/ehcache.xml


  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/app_group_activities?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

mybatis:
  type-aliases-package: org.goskyer.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
feign:
  httpclient:
    enabled: true
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 3000

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://eureka.didispace.com/eureka/
  instance:
    preferIpAddress: true
    ipAddress: 127.0.0.1


pagehelper:
  helperDialect: mysql
  reasonable: true
mapper:
  mappers:
  - tk.mybatis.mapper.common.Mapper
  identity: MYSQL